version: "3"

services:
  menu-api-prod:
    stdin_open: true
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.prod
    container_name: menu-api-prod
    hostname: menu-api
    env_file:
      - .env
    ports:
      - "3030:3000"
    restart: always
    networks:
      - menu-prod

networks:
  menu-prod:
    driver: bridge
