version: "3"

services:
  menu-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: menu-prod-api
    hostname: menu-api
    env_file:
      - .env
    ports:
      - "3030:3000"
    restart: always
    networks:
      - menu-prod
  # nginx:
  #   build:
  #     context: front
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 8081:80
  #   volumes:
  #     # - ./front/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - db-storage:/db-storage:rw

networks:
  menu-prod:
    driver: bridge
